export const SAVE_USER_REQUEST = "SAVE_USER_REQUEST";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const USER_REQUEST_SUCCESS = "USER_REQUEST_SUCCESS";
export const USER_REQUEST_FAILURE = "USER_REQUEST_FAILURE";

export const FETCH_REQUEST_TYPES_REQUEST = "FETCH_REQUEST_TYPES_REQUEST";
export const REQUEST_TYPES_SUCCESS = "REQUEST_TYPES_SUCCESS";
export const REQUEST_TYPES_FAILURE = "REQUEST_TYPES_FAILURE";